import {
  Column,
  CreateDateColumn,
  Entity,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

import { ReceptionProcess } from './reception-process.entity';
import { User } from 'src/modules/users/entities/user.entity';

export enum ProcessEventOption {
  VIGILANCIA_REGISTRA_INGRESO = 'VIGILANCIA_REGISTRA_INGRESO',
  SISTEMA_CAMBIA_ESTATUS = 'SISTEMA_CAMBIA_ESTATUS',
  LOGISTICA_CONFIRMA_PENDIENTE_DE_INGRESO = 'LOGISTICA_CONFIRMA_PENDIENTE_DE_INGRESO',
  LOGISTICA_AUTORIZA_INGRESO = 'LOGISTICA_AUTORIZA_INGRESO',
  CALIDAD_CONFIRMA_PENDIENTE_DE_ANALISIS = 'CALIDAD_CONFIRMA_PENDIENTE_DE_ANALISIS',
  CALIDAD_RECHAZA_MATERIAL = 'CALIDAD_RECHAZA_MATERIAL',
  CALIDAD_APRUEBA_MATERIAL = 'CALIDAD_APRUEBA_MATERIAL',
  PRODUCCION_CONFIRMA_PENDIENTE_DE_DESCARGA = 'PRODUCCION_CONFIRMA_PENDIENTE_DE_DESCARGA',
  PRODUCCION_INICIA_DESCARGA = 'PRODUCCION_INICIA_DESCARGA',
  PRODUCCION_FINALIZA_DESCARGA = 'PRODUCCION_FINALIZA_DESCARGA',
  LOGISTICA_CONFIRMA_CAPTURA_DE_PESO_EN_SAP = 'LOGISTICA_CONFIRMA_CAPTURA_DE_PESO_EN_SAP',
  LOGISTICA_CAPTURA_DE_PESO_EN_SAP = 'LOGISTICA_CAPTURA_DE_PESO_EN_SAP',
  CALIDAD_CONFIRMA_PENDIENTE_DE_LIBERACION_EN_SAP = 'CALIDAD_CONFIRMA_PENDIENTE_DE_LIBERACION_EN_SAP',
  CALIDAD_LIBERA_EN_SAP = 'CALIDAD_LIBERA_EN_SAP',
}

export enum ProcessState {
  VIGILANCIA_REGISTRO_INGRESO = 'VIGILANCIA_REGISTRO_INGRESO',
  LOGISTICA_PENDIENTE_DE_CONFIRMACION_INGRESO = 'LOGISTICA_PENDIENTE_DE_CONFIRMACION_INGRESO',
  LOGISTICA_PENDIENTE_DE_AUTORIZACION = 'LOGISTICA_PENDIENTE_DE_AUTORIZACION',
  CALIDAD_PENDIENTE_DE_CONFIRMACION_DE_ANALISIS = 'CALIDAD_PENDIENTE_DE_CONFIRMACION_DE_ANALISIS',
  CALIDAD_PROCESANDO = 'CALIDAD_PROCESANDO',
  CALIDAD_RECHAZO = 'CALIDAD_RECHAZO',
  CALIDAD_APROBO = 'CALIDAD_APROBO',
  PRODUCCION_PENDIENTE_DE_CONFIRMACION_PARA_DESCARGA = 'PRODUCCION_PENDIENTE_DE_CONFIRMACION_PARA_DESCARGA',
  PRODUCCION_PENDIENTE_DE_DESCARGA = 'PRODUCCION_PENDIENTE_DE_DESCARGA',
  PRODUCCION_DESCARGANDO = 'PRODUCCION_DESCARGANDO',
  PRODUCCION_DESCARGA_COMPLETADA = 'PRODUCCION_DESCARGA_COMPLETADA',
  LOGISTICA_PENDIENTE_DE_CONFIRMACION_CAPTURA_PESO_SAP = 'LOGISTICA_PENDIENTE_DE_CONFIRMACION_CAPTURA_PESO_SAP',
  LOGISTICA_PENDIENTE_DE_CAPTURA_PESO_SAP = 'LOGISTICA_PENDIENTE_DE_CAPTURA_PESO_SAP',
  LOGISTICA_CAPTURO_PESO_EN_SAP = 'LOGISTICA_CAPTURO_PESO_EN_SAP',
  CALIDAD_PENDIENTE_CONFIRMACION_LIBERACION_SAP = 'CALIDAD_PENDIENTE_CONFIRMACION_LIBERACION_SAP',
  CALIDAD_PENDIENTE_LIBERACION_EN_SAP = 'CALIDAD_PENDIENTE_LIBERACION_EN_SAP',
  CALIDAD_LIBERADO_EN_SAP = 'CALIDAD_LIBERADO_EN_SAP',
  FINALIZO_PROCESO = 'FINALIZO_PROCESO',
  FINALIZO_PROCESO_POR_RECHAZO = 'FINALIZO_PROCESO_POR_RECHAZO',
}

export enum ProcessEventRole {
  VIGILANCIA = 'VIGILANCIA',
  LOGISTICA = 'LOGISTICA',
  CALIDAD = 'CALIDAD',
  PRODUCCION = 'PRODUCCION',
  SISTEMA = 'SISTEMA',
}

@Entity({
  name: 'process_events',
})
export class ProcessEvent {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    type: 'enum',
    enum: ProcessState,
  })
  status: ProcessState;

  @Column({
    type: 'enum',
    enum: ProcessEventOption,
  })
  event: ProcessEventOption;

  @Column({
    type: 'enum',
    enum: ProcessEventRole,
  })
  role: ProcessEventRole;

  @Column('jsonb', { nullable: true })
  metadata: Record<string, any>;

  @Column({ default: true, name: 'is_active' })
  isActive: boolean;

  @ManyToOne(() => User, (user) => user.createdByProcessEvents)
  createdBy: User;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({
    name: 'updated_at',
  })
  updatedAt: Date;

  @ManyToOne(
    () => ReceptionProcess,
    (receptionProcess) => receptionProcess.events,
  )
  receptionProcess: ReceptionProcess;
}
